"""add user_id to existing tbls

Revision ID: 14d5d6cdae7a
Revises: 49c8bdb54d66
Create Date: 2025-09-22 19:04:14.255459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14d5d6cdae7a'
down_revision: Union[str, Sequence[str], None] = '49c8bdb54d66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('destinations', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_destinations_user_id'), 'destinations', ['user_id'], unique=False)
    op.create_foreign_key(None, 'destinations', 'users', ['user_id'], ['id'])
    op.add_column('knowledge_base', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_knowledge_base_user_id'), 'knowledge_base', ['user_id'], unique=False)
    op.create_foreign_key(None, 'knowledge_base', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'knowledge_base', type_='foreignkey')
    op.drop_index(op.f('ix_knowledge_base_user_id'), table_name='knowledge_base')
    op.drop_column('knowledge_base', 'user_id')
    op.drop_constraint(None, 'destinations', type_='foreignkey')
    op.drop_index(op.f('ix_destinations_user_id'), table_name='destinations')
    op.drop_column('destinations', 'user_id')
    # ### end Alembic commands ###
