"""set fkey ondelete:


Revision ID: 3491b989dccd
Revises: be8fbd1fa663
Create Date: 2025-09-25 20:28:55.126641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3491b989dccd'
down_revision: Union[str, Sequence[str], None] = 'be8fbd1fa663'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('destinations_user_id_fkey'), 'destinations', type_='foreignkey')
    op.drop_constraint(op.f('fk_destinations_org_id'), 'destinations', type_='foreignkey')
    op.create_foreign_key(None, 'destinations', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'destinations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('embeddings_knowledge_item_id_fkey'), 'embeddings', type_='foreignkey')
    op.create_foreign_key(None, 'embeddings', 'knowledge_base', ['knowledge_item_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('knowledge_base_user_id_fkey'), 'knowledge_base', type_='foreignkey')
    op.drop_constraint(op.f('knowledge_base_destination_id_fkey'), 'knowledge_base', type_='foreignkey')
    op.drop_constraint(op.f('fk_knowledge_base_org_id'), 'knowledge_base', type_='foreignkey')
    op.create_foreign_key(None, 'knowledge_base', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'knowledge_base', 'destinations', ['destination_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'knowledge_base', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'knowledge_base', type_='foreignkey')
    op.drop_constraint(None, 'knowledge_base', type_='foreignkey')
    op.drop_constraint(None, 'knowledge_base', type_='foreignkey')
    op.create_foreign_key(op.f('fk_knowledge_base_org_id'), 'knowledge_base', 'organizations', ['org_id'], ['id'])
    op.create_foreign_key(op.f('knowledge_base_destination_id_fkey'), 'knowledge_base', 'destinations', ['destination_id'], ['id'])
    op.create_foreign_key(op.f('knowledge_base_user_id_fkey'), 'knowledge_base', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'embeddings', type_='foreignkey')
    op.create_foreign_key(op.f('embeddings_knowledge_item_id_fkey'), 'embeddings', 'knowledge_base', ['knowledge_item_id'], ['id'])
    op.drop_constraint(None, 'destinations', type_='foreignkey')
    op.drop_constraint(None, 'destinations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_destinations_org_id'), 'destinations', 'organizations', ['org_id'], ['id'])
    op.create_foreign_key(op.f('destinations_user_id_fkey'), 'destinations', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
