"""remove kb fields

Revision ID: be8fbd1fa663
Revises: 9b66a7151440
Create Date: 2025-09-25 19:46:09.577177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be8fbd1fa663'
down_revision: Union[str, Sequence[str], None] = '9b66a7151440'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_base', 'source_ref')
    op.drop_column('knowledge_base', 'source_type')
    op.drop_column('knowledge_base', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_base', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('knowledge_base', sa.Column('source_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('knowledge_base', sa.Column('source_ref', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
